### ISSUE TITLE
is it open source game?

### ISSUE THREAD

**Issue by vgkgopalsaroja** [nehal076/flutter-puzzle-hack#3]

**Comment by nehal076** [comment]
K

**Comment by nehal076** [comment]
Hi, 

Yes, this game was made as a submission at [Flutter Puzzle Hack](https://flutter.dev/events/puzzle-hack).
A matter of fact it also won the Community Choice prize! 

If you want to read more about it, please read [here](https://devpost.com/software/way-for-ball).

If you want to, you can contribute to it as well by raising a pull request. :)

Thanks!
