### ISSUE TITLE
enhancement: add settings option on Game Screen as well.

### ISSUE THREAD

**Issue by nehal076** [nehal076/flutter-puzzle-hack#9]
Currently the `Settings` ⚙️ feature is only available on `start_screen`

<img height="500" alt="image" src="https://user-images.githubusercontent.com/32421196/194830668-fb1c795c-209d-4769-bc0a-9c5ed7945411.png">

It would be good if player had the `Settings ⚙️` option on Game Screen as well.

<img height="500" alt="image" src="https://user-images.githubusercontent.com/32421196/194830590-3da91244-f16b-408c-bbe9-0bb5a96a1fa1.png">

This issue is open to all.

**Comment by AnukirtiYadav** [comment]
It seems interesting. I would like to work on it.

Please assign it to me.

**Comment by nehal076** [comment]
Sure @AnukirtiYadav, go ahead. I've assigned it to you.
